# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('due_dilligence', '0002_auto_20160325_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscribedprocessors',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='usersubscribedprocessors',
            name='user',
        ),
        migrations.AddField(
            model_name='materialprocessor',
            name='subscribed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSubscribedProcessors',
        ),
    ]
